config/routes.rb
Rails.application.routes.draw do

  resources :products
  get 'home/index'
  devise_for :users
  root to: "home#index"
  resources :categories
  resources :orders
    post 'orders/:product_id', to: 'orders#create'
      
  resources :carts
  resources :carts do 
    post 'add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'add_to_cart'
    post 'remove_from_cart/item_id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Product, public: true
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :Product
      can :read, :CartItem
    end
    # Define abilities for the passed in user here. For example:
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  validates :category_name, presence: true
  has_many :products, as: :productable
end

app/models/customer.rb
class Customer < User
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
end

app/models/order_inventory.rb
class OrderInventory < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  validates :product_name, :product_description, :product_price, :product_in_strock, presence: true
  belongs_to :productable, polymorphic: true
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize: '100x100'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, as: :productable
  has_many :orders
  has_one :cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :initialize_cart

  def initialize_cart
    Cart.create(user_id: id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def add_to_cart
    product = Product.find(params[:product_id])
    cart = current_user.cart
    cart_items = cart.cart_items
    item = cart_items.find_by(product_id: product.id)
    if item
  	  item.quantity += 1
  	  item.total = item.quantity * product.product_price
  	  item.save
    else
  	  cart_items.create(product_id: product.id, quantity: 1, total: product.product_price)
    end
    cart.update(total_price: cart_items.pluck(:total).reduce(:+))
    redirect_to root_path
  end

  def remove_from_cart
    cart = current_user.cart
    cart_items = cart.cart_items
    item = cart_items.find_by(id: params[:item_id])
    if item && item.quantity > 1
	    item.quantity -= 1
	    item.total = item.quantity * item.product.product_price
	    item.save
    elsif item && item.quantity == 1
	    item.destroy
    end
    cart.update(total_price: cart_items.pluck(:total).reduce(:+))
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_cart.html.erb
<div class=" ">
                      <div class="simplebar-wrapper" style="margin: 0px -16px 0px 0px;"><div class="simplebar-height-auto-observer-wrapper"><div class="simplebar-height-auto-observer"></div></div><div class="simplebar-mask"><div class="simplebar-offset" style="right: 0px; bottom: 0px;"><div class="simplebar-content-wrapper" style="height: auto; overflow: hidden;"><div class="simplebar-content" style="padding: 0px 16px 0px 0px;">                
                      </div></div><div style="width: 0px; height: 0px;"></div></div><div class="simplebar-track simplebar-horizontal" style="visibility: hidden;"><div class="simplebar-scrollbar simplebar-visible" style="width: 0px; display: none;"></div></div><div class="simplebar-track simplebar-vertical" style="visibility: hidden;"><div class="simplebar-scrollbar simplebar-visible" style="height: 0px; display: none;"></div></div></div>
                      <div >
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="navbar navbar-expand-lg navbar-light navbar-stuck-menu mt-n2 pt-0 pb-2">
            <div class="container">
              <div class="collapse navbar-collapse" id="navbarCollapse">

app/views/shared/_footer.html.erb
<footer class="footer bg-dark pt-5">
      <div class="container">
        <div class="row pb-2">
          <div class="col-md-4 col-sm-6">
            <div class="widget widget-links widget-light pb-2 mb-4">
              <h3 class="widget-title text-light">Shop departments</h3>
              <ul class="widget-list">
                <li class="widget-list-item"><a class="widget-list-link" href="#">Sneakers &amp; Athletic</a></li>
                <li class="widget-list-item"><a class="widget-list-link" href="#">Athletic Apparel</a></li>
               <li class="widget-list-item"><a class="widget-list-link" href="#">Bags &amp; Wallets</a></li>
                <li class="widget-list-item"><a class="widget-list-link" href="#">Accessories</a></li>
                <li class="widget-list-item"><a class="widget-list-link" href="#">Sunglasses &amp; Eyewear</a></li>
                <li class="widget-list-item"><a class="widget-list-link" href="#">Watches</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4 col-sm-6">
            <div class="widget widget-links widget-light pb-2 mb-4">
              <h3 class="widget-title text-light">Account &amp; shipping info</h3>
              <ul class="widget-list">
                <li class="widget-list-item"><a class="widget-list-link" href="#">Your account</a></li>
                <li class="widget-list-item"><a class="widget-list-link" href="#">Delivery info</a></li>
                <li class="widget-list-item"><a class="widget-list-link" href="#">Taxes &amp; fees</a></li>
              </ul>
            </div>
            <div class="widget widget-links widget-light pb-2 mb-4">
              <h3 class="widget-title text-light">About us</h3>
              <ul class="widget-list">
                <li class="widget-list-item"><a class="widget-list-link" href="#">About company</a></li>
                <li class="widget-list-item"><a class="widget-list-link" href="#">Our team</a></li>
                <li class="widget-list-item"><a class="widget-list-link" href="#">Careers</a></li>
                <li class="widget-list-item"><a class="widget-list-link" href="#">News</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="widget pb-2 mb-4">
              <h3 class="widget-title text-light pb-1">Stay informed</h3>
              <form class="subscription-form validate" action="https://studio.us12.list-manage.com/subscribe/post?u=c7103e2c981361a6639545bd5&amp;amp;id=29ca296126" method="post" name="mc-embedded-subscribe-form" target="_blank" novalidate="">
                <div class="input-group flex-nowrap"><i class="ci-mail position-absolute top-50 translate-middle-y text-muted fs-base ms-3"></i>
                  <input class="form-control rounded-start" type="email" name="EMAIL" placeholder="Your email" required="">
                  <button class="btn btn-primary" type="submit" name="subscribe">Subscribe*</button>
                </div>
                <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                <div style="position: absolute; left: -5000px;" aria-hidden="true">
                  <input class="subscription-form-antispam" type="text" name="b_c7103e2c981361a6639545bd5_29ca296126" tabindex="-1">
                </div>
                <div class="form-text text-light opacity-50">*Subscribe to our newsletter to receive early discount offers, updates and new products info.</div>
                <div class="subscription-status"></div>
              </form>
            </div>
            <div class="widget pb-2 mb-4">
              <h3 class="widget-title text-light pb-1">Download our app</h3>
              <div class="d-flex flex-wrap">
                <div class="me-2 mb-2"><a class="btn-market btn-apple" href="#" role="button"><span class="btn-market-subtitle">Download on the</span><span class="btn-market-title">App Store</span></a></div>
                <div class="mb-2"><a class="btn-market btn-google" href="#" role="button"><span class="btn-market-subtitle">Download on the</span><span class="btn-market-title">Google Play</span></a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

app/views/shared/_header.html.erb
<header class="shadow-sm">

        <!-- Remove "navbar-sticky" class to make navigation bar scrollable with the page.-->
        <div class="navbar-sticky bg-light">
          <div class="navbar navbar-expand-lg navbar-light">
            <div class="container"><a class="navbar-brand d-none d-sm-block flex-shrink-0" href="/"><%= image_tag "head.png",width:"50",height: "50", class:"lower-img"%></a><a class="navbar-brand d-sm-none flex-shrink-0 me-2" href="/"><img src="/" alt="Cartzilla"></a>
              <div class="input-group d-none d-lg-flex mx-4">
                <input class="form-control rounded-end pe-5" type="text" placeholder="Search for products"><i class="ci-search position-absolute top-50 end-0 translate-middle-y text-muted fs-base me-3"></i>
              </div>
            <div class="navbar-toolbar d-flex flex-shrink-0 align-items-center">
               <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"><span class="navbar-toggler-icon"></span></button><a class="navbar-tool navbar-stuck-toggler" href="#"><span class="navbar-tool-tooltip">Expand menu</span>
                 <div class="navbar-tool-icon-box"><i class="navbar-tool-icon ci-menu"></i></div></a><a class="navbar-tool d-none d-lg-flex" href="account-wishlist.html"><span class="navbar-tool-tooltip">Wishlist</span>
                 <div class="navbar-tool-icon-box"> </i></div></a><a class="navbar-tool ms-1 ms-lg-0 me-n1 me-lg-2" href="/" data-bs-toggle="modal">
                 <div class="navbar-tool-icon-box"><i class="navbar-tool-icon ci-user"></i></div>
                 <div class="navbar-tool-text ms-n3"><small>Hello</small>My Account</div></a>

                <div class="navbar-tool dropdown ms-3"><a class="navbar-tool-icon-box bg-secondary "><span class="navbar-tool-label">4</span><i class="navbar-tool-icon ci-cart"></i><a class="navbar-tool-text" ><small></small><%= link_to 'Cart', carts_path %></a>
                  <%= render 'shared/cart' %>
                    <div class="input-group d-lg-none my-3"><i class="ci-search position-absolute top-50 start-0 translate-middle-y text-muted fs-base ms-3"></i>
                      <input class="form-control rounded-start" type="text" placeholder="Search for products">
                    </div>
                  <ul class="navbar-nav navbar-mega-nav pe-lg-2 me-lg-2">
                      <div class="dropdown-menu px-2 pb-4">
                        <div class="d-flex flex-wrap flex-sm-nowrap">
                          <div class="mega-dropdown-column pt-3 pt-sm-4 px-2 px-lg-3">
                            <div class="widget widget-links"><a class="d-block overflow-hidden rounded-3 mb-3" href="#"><img src="img/shop/departments/01.jpg" alt="Clothing"></a>
                              <h6 class="fs-base mb-2">Mobiles</h6>
                            </div>
                  </ul>
                <!-- Primary menu-->
                <ul class="navbar-nav">
                  <li class="nav-item dropdown active"><a class="nav-link dropdown-toggle"  data-bs-toggle="dropdown"><%= link_to 'Home', root_path, class:"nav-link dropdown-toggle "%></li>
                  <li class="nav-item dropdown"><a class="nav-link dropdown-toggle"  data-bs-toggle="dropdown"><%= link_to 'Orders', orders_path, class:"nav-link dropdown-toggle"%>
                    <li class="nav-item dropdown"><a class="nav-link dropdown-toggle"  data-bs-toggle="dropdown" data-bs-auto-close="outside"><%= link_to 'Add Product', new_product_path, class:"nav-link dropdown-toggle"%></li>

                  <% if user_signed_in? %>
                    <li class="nav-item dropdown"><a class="nav-link dropdown-toggle"  data-bs-toggle="dropdown"><%= link_to 'logout', destroy_user_session_path, method: :delete,class:"nav-link dropdown-toggle" %></li>
                  <% else %>
                    <li class="nav-item dropdown"><a class="nav-link dropdown-toggle"  data-bs-toggle="dropdown"><%= link_to 'Sign in', new_user_session_path, class:"nav-link dropdown-toggle" %></li>
                  <%end%>
                  <li class="nav-item dropdown"><a class="nav-link dropdown-toggle"  data-bs-toggle="dropdown" data-bs-auto-close="outside"><%= link_to 'Category', categories_path, class:"nav-link dropdown-toggle"%>   </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
  </header>