config/routes.rb
Rails.application.routes.draw do

  resources :products
  get 'home/index'
  devise_for :users
  root to: "home#index"
  resources :categories
  resources :orders
    post 'orders/:product_id', to: 'orders#create'
      
  resources :carts
  resources :carts do 
    post 'add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'add_to_cart'
    post 'remove_from_cart/item_id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Product, public: true
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :Product
      can :read, :CartItem
    end
    # Define abilities for the passed in user here. For example:
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  validates :category_name, presence: true
  has_many :products, as: :productable
end

app/models/customer.rb
class Customer < User
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
end

app/models/order_inventory.rb
class OrderInventory < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  validates :product_name, :product_description, :product_price, :product_in_strock, presence: true
  belongs_to :productable, polymorphic: true
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize: '100x100'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, as: :productable
  has_many :orders
  has_one :cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :initialize_cart

  def initialize_cart
    Cart.create(user_id: id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def add_to_cart
    product = Product.find(params[:product_id])
    cart = current_user.cart
    cart_items = cart.cart_items
    item = cart_items.find_by(product_id: product.id)
    if item
  	  item.quantity += 1
  	  item.total = item.quantity * product.product_price
  	  item.save
    else
  	  cart_items.create(product_id: product.id, quantity: 1, total: product.product_price)
    end
    cart.update(total_price: cart_items.pluck(:total).reduce(:+))
    redirect_to root_path
  end

  def remove_from_cart
    cart = current_user.cart
    cart_items = cart.cart_items
    item = cart_items.find_by(id: params[:item_id])
    if item && item.quantity > 1
	    item.quantity -= 1
	    item.total = item.quantity * item.product.product_price
	    item.save
    elsif item && item.quantity == 1
	    item.destroy
    end
    cart.update(total_price: cart_items.pluck(:total).reduce(:+))
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @products = Product.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  def index
    @orders = current_user.orders
  end

  def show
    @order_items = @order.order_items
  end

  def create
    user = User.find(params[:user_id])
    cart = user.cart
    cart_items = cart.cart_items
    order = Order.create(user_id: user.id)
    cart_items.each do |cart_item|
      order.order_items.create(product_id: cart_item.product_id, total: cart_item.total)
      cart_item.destroy
    end
    cart.update(total_price: 0)
    order.update(total_price: order.order_items.pluck(:total).sum)
    cart.total_price

    redirect_to root_path
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show;  end

  def edit;  end

  def create
    @user = current_user
    @product = @user.products.new(product_params)
    @product.user_id = current_user.id
    if @product.save
    UserMailer.new_product_email(@product, @user.email).deliver_now
    # SendNotificationsJob.perform_now(@product)
    redirect_to @product
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to root_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:product_name, :product_description, :product_in_strock,
                                    :product_price, :product_size, :user_id, :category_id,
                                    images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
    <h1>All Products</h1>
    <div class="row ml-2">
      <div class="col-12 col-md-7 col-lg-9 bg-light rounded-lg img-thumbnail">
        <div class="row justify-content-center py-4">
          <% @products.each do |product| %>
            <div class="card my-2 col-12 col-md-4 col-lg-3 rounded-lg mx-2 card-shadow">
              <div class="text-center">
                <% product.images.each do |image| %>
                  <%= image_tag image, class: "card-img-top rounded-lg border m-2 w-50", :size => "180x180"  %>
                <% end %>
              </div>
            <div class="card-body text-center">
              <h5 class="card-title">Name- <%= product.product_name %></h5>
              <small class="text-muted d-block">Price- <%= product.product_price %></small>
              <small class="text-muted d-block">Description- <%= product.product_description %></small>
              <small class="text-muted d-block">Size- <%= product.product_size %><br></small>
              <small class="text-muted d-block">Stock-  <%= product.product_in_strock%></small>
            </div>
              <div class="card-body p-1 pb-2">
                <div class="" style="bottom:2px;height: 45%">
                  <% if can? :update, product %>
                    <%= link_to 'Show', product %>
                  <% end %>
                  <% if can? :update, product %>
                    <%= link_to 'Edit', edit_product_path(product)  %>
                  <% end %>
                  <% if can? :delete, product %>
                    <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }  %>
                  <% end %>
                  <%= button_to 'Add to cart',  cart_add_to_cart_path(product_id: product, cart_id: current_user.cart.id), :method => :post, remote: true, class:"btn btn-success" %>
               </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
<% end %>