config/routes.rb
Rails.application.routes.draw do

  resources :products
  get 'home/index'
  devise_for :users
  root to: "home#index"
  resources :categories
  resources :orders
    post 'orders/:product_id', to: 'orders#create'
      
  resources :carts
  resources :carts do 
    post 'add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'add_to_cart'
    post 'remove_from_cart/item_id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Product, public: true
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :Product
      can :read, :CartItem
    end
    # Define abilities for the passed in user here. For example:
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  validates :category_name, presence: true
  has_many :products, as: :productable
end

app/models/customer.rb
class Customer < User
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
end

app/models/order_inventory.rb
class OrderInventory < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  validates :product_name, :product_description, :product_price, :product_in_strock, presence: true
  belongs_to :productable, polymorphic: true
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize: '100x100'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, as: :productable
  has_many :orders
  has_one :cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :initialize_cart

  def initialize_cart
    Cart.create(user_id: id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def add_to_cart
    product = Product.find(params[:product_id])
    cart = current_user.cart
    cart_items = cart.cart_items
    item = cart_items.find_by(product_id: product.id)
    if item
  	  item.quantity += 1
  	  item.total = item.quantity * product.product_price
  	  item.save
    else
  	  cart_items.create(product_id: product.id, quantity: 1, total: product.product_price)
    end
    cart.update(total_price: cart_items.pluck(:total).reduce(:+))
    redirect_to root_path
  end

  def remove_from_cart
    cart = current_user.cart
    cart_items = cart.cart_items
    item = cart_items.find_by(id: params[:item_id])
    if item && item.quantity > 1
	    item.quantity -= 1
	    item.total = item.quantity * item.product.product_price
	    item.save
    elsif item && item.quantity == 1
	    item.destroy
    end
    cart.update(total_price: cart_items.pluck(:total).reduce(:+))
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show;  end

  def edit;  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:category_name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @products = Product.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  def index
    @orders = current_user.orders
  end

  def show
    @order_items = @order.order_items
  end

  def create
    user = User.find(params[:user_id])
    cart = user.cart
    cart_items = cart.cart_items
    order = Order.create(user_id: user.id)
    cart_items.each do |cart_item|
      order.order_items.create(product_id: cart_item.product_id, total: cart_item.total)
      cart_item.destroy
    end
    cart.update(total_price: 0)
    order.update(total_price: order.order_items.pluck(:total).sum)
    cart.total_price

    redirect_to root_path
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show;  end

  def edit;  end

  def create
    @user = current_user
    @product = @user.products.new(product_params)
    @product.user_id = current_user.id
    if @product.save
    UserMailer.new_product_email(@product, @user.email).deliver_now
    # SendNotificationsJob.perform_now(@product)
    redirect_to @product
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to root_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:product_name, :product_description, :product_in_strock,
                                    :product_price, :product_size, :user_id, :category_id,
                                    images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/carts/_cart.html.erb
<details>
  <summary>Cart</summary>
  <ul>
    <% if @cart&.cart_items&.empty? %>
    <p> No items in cart</p>
    <% else %>
    <% @cart.cart_items.each do |cart_item| %>
<table class="table table-responsive">
  <thead>
    <tr>
      <th scope="col">Product Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
    <tr>
      <td><%= cart_item.product.product_name %></td>
      <td><%= cart_item.quantity %></td>
      <td><%=  cart_item.total %></td>
      <td><%= link_to 'Remove Item',  cart_remove_from_cart_path(item_id: cart_item.id, cart_id: current_user.cart.id), :method => :post %></td>
       <% end %>
    </tr>
</table>
     <hr>
      <p>Total <%= @cart.total_price %></p>
      <%= button_to 'Pay', orders_path(user_id: current_user.id), :method => :post, data: { confirm: 'Are you sure? to placed order' }, class: "btn btn-danger" %>
      <% end %>
</details>

app/views/carts/add_to_cart.html.erb
<details>
  <summary>Cart</summary>
  <ul>
    <% if @cart&.cart_items&.empty? %>
    <p> No items in cart</p>
    <% else %>
    <% @cart.cart_items.each do |cart_item| %>
<table class="table">
  <thead>
    <tr></tr>
      <th scope="col">Product Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tr>

      <td><%= cart_item.product.product_name %></td>
      <td><%= cart_item.quantity %></td>
      <td><%=  cart_item.total %></td>
      <td><%= link_to 'Remove Item',  cart_remove_from_cart_path(item_id: cart_item.id, cart_id: current_user.cart.id), :method => :post %></td>
       <% end %>
  </tr>
</table>
     <hr>
      <p>Total <%= @cart.total_price %></p>
      <%= button_to 'Pay', orders_path(user_id: current_user.id), :method => :post, data: { confirm: 'Are you sure? to placed order' } %>
      <% end %>
</details>
<% end %>

app/views/carts/index.html.erb
<% if user_signed_in? %>
<br><br>

<table class="table" border="1">
  <thead>
  <tr>
    <th scope="col">Product Name</th>
    <th scope="col">Quantity</th>
    <th scope="col">Price</th>
    <th scope="col">Actions</th>
    <th scope="col">Remove</th>
    <th scope="col">Total Amount</th>
    </tr>
  </thead>
  <tr>
    <% current_user.cart.cart_items.each do |cart_item| %>
      <td><%= cart_item.product.product_name %></td>
      <td><%= cart_item.quantity %></td>
      <td><%= cart_item.product.product_price %></td>
      <td><div style="width:100px; height:100px">
        <% cart_item.product.images.each do |image| %>
            <%= image_tag image %>
        <% end %></div></td>
      <td><%= link_to 'Remove Item', cart_remove_from_cart_path(item_id: cart_item.id, cart_id: current_user.cart.id), :method => :post , class:"btn btn-danger" %></td>
      <td><%= cart_item.total %></td>
  </tr>
    <% end %>
</table>
    <%= button_to 'Pay', orders_path(product_id: @product, user_id: current_user.id), :method => :post, data: { confirm: 'Are you sure? to placed order' }, class: "btn btn-danger" %>
    <p class="text-end "><strong align="text-align:left;">Total Amount= <%= current_user.cart.total_price %></strong></p>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :category_name %>
  <%= form.text_field :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table class="table table-striped">
  <thead>
    <tr>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category_name %></td>
        <% if can? :update, category %>
        <td><%= link_to 'Show', category_path(category), class:"btn btn-primary"  %></td>
        <% end %>
        <% if can? :update, category %>
        <td><%= link_to 'Edit', edit_category_path(category), class:"btn btn-success"  %></td>
        <% end %>
        <% if can? :delete, category %>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"  %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, @categories %>
  <%= link_to 'New Category', new_category_path %>
<% end %>
<%= link_to 'Back', root_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<br><br>
<p id="notice"><%= notice %></p>
<div class="card container shadow p-3 mb-5 bg-white rounded">
  <div class="card-body">
    <p>
      <% @category.products.each do |product| %>
        <strong>Product Name:</strong>
        <%= product.product_name%><br>
        <% end %>
    </p>
  </div>
</div>
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/orders/_form.html.erb
<%= form_with model: @order do |form| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Orders</h1>

<%= render 'form', post: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<% if user_signed_in? %>
  <br><br>

  <table class="table" border="1">
    <thead>
      <tr>
        <th scope="col">Order ID</th>
        <th scope="col">Ordered at</th>
        <th scope="col">Total Price</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tr>
      <% @orders.each do |order| %>
        <td><%= order.id %></td>
        <td><%= order.created_at %></td>
        <td><%= order.total_price %></td>
        <td><%= link_to "Check Order", order_path(order), class: "btn btn-primary" %></td>
    </tr>
      <% end %>
  </table>
<% end %>

app/views/orders/new.html.erb
<h1>New Product</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<% if user_signed_in? %>
<br><br>

<table class="table" border="1">
  <thead>
  <tr>
    <th scope="col">Product Name</th>
    <th scope="col">Price</th>
    <th scope="col">Total Amount</th>
    </tr>
  </thead>
  <tr>
  <% @order_items.each do |order_item| %>
    <td><%= order_item.product.product_name %></td>
    <td><%= order_item.product.product_price %></td>
    <td><%= order_item.total %></td>
    </tr>
  <% end %>
</table>
<p class="text-end "><strong align="text-align:left;">Total Amount= <%= @order.total_price %></strong></p>
<% end %>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-md-6">
  <div class="field ">
    <%= form.label :Product_name %>&nbsp;&nbsp;&nbsp;&nbsp;
    <%= form.text_field :product_name, id:"autoSizingInput"  %>
  </div>

  <div class="field">
    <%= form.label :Product_price%> &nbsp;&nbsp;&nbsp;&nbsp;
    <%= form.text_field :product_price, id:"autoSizingInput" %>
  </div>

  <div class="field">
    <%= form.label :image %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= form.file_field :images, multiple: true, id:"autoSizingInput" %>
  </div>

  <div class="field">
    <%= form.label :Product_size %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= form.text_field :product_size, id:"autoSizingInput" %>
  </div>

  <div class="field">
    <%= form.label :product_in_stock %>
    <%= form.text_field :product_in_strock, id:"autoSizingInput" %>
  </div><br>

  <div class="field">
    <%= form.label :product_description %>
    <%= form.text_area :product_description,id:"autoSizingInput" %>
  </div>
 </div><br>

  Select Category<%= form.select :category_id, Category.all.map {|c| [c.category_name, c.id] }%>

  <div class="actions class="btn btn-primary">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', post: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Size</th>
      <th>In Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.product_description%></td>
        <td><%= product.product_price%></td>
        <td><%= product.product_size%></td>
        <td><%= product.product_in_strock%></td>
        <% product.images.each do |image| %>
          <td  style="width:50px; height:50px"><%= image_tag image %> </td>
        <% end %>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Product', new_product_path %>
<%= link_to 'Back', root_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', user: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<br><br>
<p id="notice"><%= notice %></p>
<div class="card container shadow p-3 mb-5 bg-white rounded">
  <div class="card-body">
    <div class="text-center">
      <% @product.images.each do |image| %>
        <%= image_tag image, style: "width:150px;height:150px;", class: "card-img-top rounded-lg border border-dark m-2" %>
      <% end %>
    <p>
      <strong>Product Name:</strong>
        <%= @product.product_name %>
    </p>

    <p>
      <strong>Product Description:</strong>
        <%= @product.product_description %>
    </p>

    <p>
      <strong>Product name:</strong>
      <%= @product.product_price %>
    </p>

    <%= link_to 'Edit', edit_product_path(@product) %> |
    <%= link_to 'Back', root_path %>
  </div>
</div>